object Versions {
    const val ankoVersion = "0.10.8"
    const val appCompatVersion = "1.1.0"
    const val constraintLayoutVersion = "1.1.3"
    const val espressoVersion = "3.2.0"
    const val coroutinesVersion = "1.3.7"
    const val gradleVersion = "4.0.0"
    const val jacocoVersion = "0.8.5"
    const val junitVersion = "4.13"
    const val kotlinVersion = "1.3.72"
    const val recyclerViewVersion = "1.1.0"
    const val robolectricVersion = "4.3.1"
    const val screengrabVersion = "1.1.0"
    const val serializationVersion = "0.20.0"
    const val testVersion = "1.2.0"
}