$devices_ios = ["iPhone X"]
$devices_android = ""

platform :ios do
  lane :tests do
    swiftlint
    run_tests(devices: $devices_ios, clean: true, code_coverage: true, project: "ios/SwiftKotlination/SwiftKotlination.xcodeproj")
  end

  lane :screenshots do
    capture_ios_screenshots(devices: $devices_ios, clear_previous_screenshots: true, project: "ios/SwiftKotlination/SwiftKotlination.xcodeproj")
  end
end

platform :android do
  lane :tests do

  end

  lane :screenshots do

  end
end
